### ISSUE TITLE
Implement authentication enforcement on proxy client scenario

### ISSUE THREAD

**Issue by adamantivm** [creativa77/rocon_web_proxy_server#27]
Make sure to implement the necessary logic between the proxy client and the proxy server to disconnect clients that don't provide authentication (or fail the authentication test) when the proxy client is configured to perform authentication. Similar to [this rosbrdge_server logic](https://github.com/creativa77/rosbridge_suite/compare/rocon-web-proxy...creativa77:multiple_user_authentication#diff-c440bf386ee54acaddef58a4e7613911R95)

**Comment by adamantivm** [comment]
Isn't this now implemented by #31 @pablisho? If so, please close this issue

**Comment by pablisho** [comment]
Closed because it's implemented in #31
